# Características generales de la base de datos

Este código presenta estadísticos básicos de la base de datos

In [12]:
# Importación de bibliotecas necesarias
import numpy as np  # Para cálculos numéricos
import pandas as pd  # Para manipulación y análisis de datos

# Ruta de acceso
file_path = 'C:/Users/monts/OneDrive/Documentos/UCR/herramientas ciencias de datos II/proyecto_herramientas_ii/data/diabetes.csv'

# Leer el archivo CSV en un DataFrame 
data = pd.read_csv(file_path)

data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [13]:
def caracteristicas_de_una_columna(dataframe, columna):
        caracteristicas_columna = dataframe[columna]
        caracteristicas = {}

        if caracteristicas_columna.dtype in ['int64', 'float64']:  
            caracteristicas['Media'] = round(caracteristicas_columna.dropna().mean(), 2)
            caracteristicas['Mediana'] = round(caracteristicas_columna.dropna().median(), 2)
            caracteristicas['Mínimo'] = round(caracteristicas_columna.dropna().min(), 2)
            caracteristicas['Máximo'] = round(caracteristicas_columna.dropna().max(), 2)
            caracteristicas['Varianza'] = round(caracteristicas_columna.dropna().var(), 2)
            
        
        conteo_valores = caracteristicas_columna.dropna().value_counts()
        max_valor = conteo_valores.max()
        nombres_max = conteo_valores[conteo_valores == max_valor].index.tolist()
        imprimir = ', '.join(str(nombre) for nombre in nombres_max) 
        caracteristicas['Moda'] = imprimir

        caracteristicas['Datos faltantes'] = caracteristicas_columna.isnull().sum()

        return caracteristicas
    
def caracteristicas_dataframe_columnas(dataframe):
    resultados = {}
    for columna in dataframe.columns:
        resultados[columna] = caracteristicas_de_una_columna(dataframe, columna)
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

In [14]:
df_resultados = caracteristicas_dataframe_columnas(data)
print(df_resultados)

                Pregnancies  Glucose BloodPressure SkinThickness   Insulin  \
Media                  3.85   120.89         69.11         20.54      79.8
Mediana                 3.0    117.0          72.0          23.0      30.5
Mínimo                    0        0             0             0         0
Máximo                   17      199           122            99       846
Varianza              11.35  1022.25        374.65        254.47  13281.18
Moda                      1  99, 100            70             0         0
Datos faltantes           0        0             0             0         0

                   BMI DiabetesPedigreeFunction    Age Outcome
Media            31.99                     0.47  33.24    0.35
Mediana           32.0                     0.37   29.0     0.0
Mínimo             0.0                     0.08     21       0
Máximo            67.1                     2.42     81       1
Varianza         62.16                     0.11  138.3    0.23
Moda              32.0             0.258, 0.254     22       0
Datos faltantes      0                        0      0       0